### ISSUE TITLE
Error when trying to drop.

### ISSUE THREAD

**Issue by gautamgolakiya** [luckylooke/dragular#102] opened 2016-08-04 06:54 UTC
Hi @luckylooke,

I would like to be able drag n drop by for my angular project. I set up my container with the josn and it's work fine as drag and drop but when i  am trying to call events it returns me an error in console like this

1) dragular.js:1280 Uncaught TypeError: Cannot read property 'parentNode' of null
2) dragular.js:1201 Uncaught TypeError: Cannot read property 'nextElementSibling' of null.

Here is the fiddle for that example i am working on  https://jsfiddle.net/vff4acwh/7/

Can you help me out where i am gonna wrong.
Thank You.

**Comment by luckylooke** [comment] 2016-08-11 13:40
Sorry for late answer, I am quite busy.. looks like a bug.. I will try to fix it ASAP, but Im away this weekend, so if I dont make it until tomorrow, it will be next week. Thanks for understanding.

**Comment by luckylooke** [comment] 2016-08-15 20:24
I dont know if it was by design from you, but you made nested drag n drop containers by initialising dragular on two levels of your structure. Anyway dragular should be OK with nested environment, so I will be investigate the reason in near future. Until then you can look at edited fiddle [here](https://jsfiddle.net/ndujsabm/)

**Comment by gautamgolakiya** [comment] 2016-08-16 05:10
Thanks for help, now i have one more question about it how can i find the which container is drop and where it is drop (i mean suppose i have two container and i want to drag task in between those two so how can i find in which container it is drop).
Thanks again for your time.

**Comment by luckylooke** [comment] 2016-08-16 07:30
In [the fiddle](https://jsfiddle.net/ndujsabm/) see console log occurred on drop event. There are provided parameters to listener documented [here](https://github.com/luckylooke/dragular#events). See the line with dragulardrop event. Second parameter is target-container, thats the one where item was dropped.

**Comment by luckylooke** [comment] 2016-08-16 10:05
So it wasn`t bug, it was not properly handled nested containers. I have made some protective conditional statements in the source code anyway.

**Closed by luckylooke** 2016-08-16 10:05 UTC

**Comment by gautamgolakiya** [comment] 2016-08-16 10:59
Hi luckylooke,
I am appreciate your help but again i m stuck with the drop_index in drop event. when i am trying to drop any item at any container and trying to get drop_index it returns me undefined. you can check fiddle over <a href="https://jsfiddle.net/vff4acwh/9/">here</a>

**Comment by luckylooke** [comment] 2016-08-16 19:46
Yes it is a bug, thanks for reporting, I have made extra issue for better tracking.
