### ISSUE TITLE
Can't click on buttons & inputs

### ISSUE THREAD

**Issue by forcewill** [luckylooke/dragular#87] opened 2016-05-06 10:40 UTC
I cannot click on any buttons and inputs inside a container.

**Comment by luckylooke** [comment] 2016-05-12 21:22
Please try to reproduce your scenario at jsfiddle, codepen or wherever online so I can investigate. I have made quick test and everything seems to be working. http://prntscr.com/b3cfwc

**Comment by luckylooke** [comment] 2016-05-31 18:39
Closing due to idle.

**Closed by luckylooke** 2016-05-31 18:39 UTC
Labels: needs: more info

**Comment by DiegoHuang** [comment] 2016-10-28 08:32
Hi luckylooke, 
I face the same problem in example "NestedNgRepeat",  input field doesnt work on the second nested "exampleCell".

**Comment by luckylooke** [comment] 2016-10-31 12:17
@DiegoHuang I have found the problem, thanks for reporting, fixed in v4.2.4 ;)

**Comment by DiegoHuang** [comment] 2016-11-01 07:12
It work well now, thank you! ：)
